import artistsImg from "../../../../Images/author.jpg";
import market01 from "../../../../Images/market-01.jpg";
const ItemsDetails = [
  {
    id: 1,
    title: "Music Art Super Item",
    price: "$8,240.50",
    category: ["All", "Music Art"],
    img: market01,
    artistImg: artistsImg,
    artistName: "Liberty Artist",
    eth: "2.03 ETH",
    expireTime: "4D 08H 15M 42S",
    expireDate: "July 24th, 2022",
  },
  {
    id: 2,
    title: "Blockchain Music Design",
    price: "$8,200.50",
    category: ["All", "Music Art", "Blockchain"],
    img: market01,
    artistImg: artistsImg,
    artistName: "Liberty Artist",
    eth: "2.44 ETH",
    expireTime: "5D 10H 22M 24S",
    expireDate: "July 18th, 2022",
  },
  {
    id: 3,
    title: "Digital Crypto Artwork",
    price: "$7,200.50",
    category: ["All", "Digital Art"],
    img: market01,
    artistImg: artistsImg,
    artistName: "Liberty Artist",
    eth: "2.03 ETH",
    expireTime: "2D 06H 30M 25S",
    expireDate: "July 26th, 2022",
  },
  {
    id: 4,
    title: "Digital Art Item",
    price: "$8,400.50",
    category: ["All", "Digital Art"],
    img: market01,
    artistImg: artistsImg,
    artistName: "Liberty Artist",
    eth: "2.50 ETH",
    expireTime: "4D 08H 32M 18S",
    expireDate: "July 16th, 2022",
  },
  {
    id: 5,
    title: "Blockchain Item One",
    price: "$6,600.00",
    category: ["All", "Blockchain"],
    img: market01,
    artistImg: artistsImg,
    artistName: "Liberty Artist",
    eth: "3.64 ETH",
    expireTime: "6D 05H 40M 50S",
    expireDate: "July 28th, 2022",
  },
  {
    id: 6,
    title: "Virtual Currency Art",
    price: "$8,800.50",
    category: ["All", "Virtual"],
    img: market01,
    artistImg: artistsImg,
    artistName: "Liberty Artist",
    eth: "2.44 ETH",
    expireTime: "3D 05H 20M 58S",
    expireDate: "July 14th, 2022",
  },
];

export default ItemsDetails;
